### ISSUE TITLE
gpg: Can't check signature: No public key

### ISSUE THREAD

**Issue by tuniemela** [snyk/driftctl-action#3]
Setup:
```
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run driftctl
        uses: cloudskiff/driftctl-action@v1.0.2
        with:
          version: 0.9.0
```
Output:
```
gpg: directory '/github/home/.gnupg' created
gpg: keybox '/github/home/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: No name
Downloading driftctl:0.9.0
No installed versions of driftctl matched '0.9.0', let's install it
gpg: Signature made Tue May 25 13:54:13 2021 UTC
gpg:                using EDDSA key 277666005A7F01D484F6376DACC776A79C824EBD
gpg:                issuer "security@cloudskiff.com"
gpg: Can't check signature: No public key
PGP signature rejected!
Installation of version 0.9.0 failed
Failed to get version from dctlenv-version-name
```
